### PR TITLE
Limit content image width to 100%

### PR DESCRIPTION
**Pull request by bazilio91**
Before fix:

After fix:

### CODE REVIEW

**Comment by samdark** [comment]
Looks much better. @cebe merge?

**Comment by cebe** [comment]
it does but I was quite sure this was already implemented... will check that.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2-apidoc/blob/master/templates/bootstrap/assets/css/api.css#L101-L103

wonder why this rule does not apply in this case...

**Comment by bazilio91** [comment]
@cebe https://github.com/yiisoft/yii2-apidoc/blob/master/templates/bootstrap/assets/AssetBundle.php#L22

**Comment by cebe** [comment]
Oops... seems I need to clean something up here :)
Merged this for now.

**Comment by cebe** [comment]
Thank you!

**Pull request merged**
