### PR TITLE
Fix `ApiMarkdown::renderLink()`

### PR DESCRIPTION
**Pull request by WinterSilence**
Normalizes `.md` URLs

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #286

### CODE REVIEW

**Comment by WinterSilence** [comment]
@rob006 what's wrong?

**Comment by rob006** [comment]
@WinterSilence You didn't explained your change and I'm not sure how these changes could help with https://github.com/yiisoft/yii2-apidoc/issues/286. Right now `renderLink()` implementation just don't make any sense - you have a lot of dead code, because both `preg_replace_callback()` calls do exactly the same.

https://github.com/yiisoft/yii2-apidoc/issues/286 is weird, because there are 2 nearly identical links, but only one of them works. Did you figure out what is so special about second link that it is incorrectly rendered?

**Comment by WinterSilence** [comment]
@rob006
> Did you figure out what is so special about second link that it is incorrectly rendered?

link don't have `guide:` prefix and that's prefix is bad idea, because prefixed links not works in github wiki

**Comment by rob006** [comment]
> link don't have `guide:` prefix: `[Filtering Data](output-data-widgets.md#filtering-data) and [Separate Filter Form](output-data-widgets.md#separate-filter-form)`

First link does not have `guide` prefix and it works, so that's not it.

**Comment by WinterSilence** [comment]
@rob006 what link are you talking about?

**Comment by WinterSilence** [comment]
@rob006 aaa... you about this, no greedy condition

**Comment by arogachev** [comment]
Thanks for contributing and sorry for the late review again.

I checked these changes locally and unfortunately they do nothing. Both before and after them the last mentioned problematic link is rendered like this:

```html
<a href="guide-output-data-widgets.html#separate-filter-form">Separate Filter Form</a>
```

So I guess either the rendered version shown at production site is outdated or there is some additional post processing done at site level.

The bottom line is can't be merged in the current state.

**Comment by WinterSilence** [comment]
@arogachev how you test it? `ApiMarkdown::process('[Filtering Data](output-data-widgets.md#filtering-data) and [Separate Filter Form](output-data-widgets.md#separate-filter-form)`   returns correct result

**Comment by arogachev** [comment]
1. Using `guide` console command on the whole `en` guide (before and after the changes).
2. Might be something [here](https://github.com/yiisoft-contrib/yiiframework.com/blob/2a52930122d78eb5c1fed9d0e08915c71d8b0a78/commands/GuideController.php), need to check more thoroughly.

**Comment by WinterSilence** [comment]
@arogachev 1. this PR changed only `yii\apidoc\helpers\ApiMarkdown`, incorrect test it by `guide` command
2. as I'm already told you, this is bug in apidoc

**Comment by rob006** [comment]
@WinterSilence Can you provide failing unit tests and then show how your change fixes it?

**Comment by WinterSilence** [comment]
@rob006

**Pull request closed without merging**
