### PR TITLE
 undefined index subjectName[0] fix

### PR DESCRIPTION
**Pull request by santosh-1265**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by cebe** [comment]
how can this be empty? A class with empty property or method name?

**Comment by santosh-1265** [comment]
Rendering files: 89% (3112/3472) ETA: 16 sec. PHP Notice 'yii\base\ErrorException' with message 'Uninitialized string offset: 0'

in /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/models/TypeDoc.php:57

Stack trace:
#0 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/models/TypeDoc.php(57): yii\base\ErrorHandler->handleError(8, 'Uninitialized s...', '/home/cloudadic...', 57, Array)
#1 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/models/ClassDoc.php(45): yii\apidoc\models\TypeDoc->findSubject('')
#2 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdownTrait.php(55): yii\apidoc\models\ClassDoc->findSubject('')
#3 /home/cloudadic/service/vendor/cebe/markdown/Parser.php(345): yii\apidoc\helpers\ApiMarkdown->parseApiLinks('[[HTMLPurifier_...')
#4 /home/cloudadic/service/vendor/cebe/markdown/Parser.php(85): cebe\markdown\Parser->parseInline('[[HTMLPurifier_...')
#5 /home/cloudadic/service/vendor/yiisoft/yii2/helpers/BaseMarkdown.php(84): cebe\markdown\Parser->parseParagraph('[[HTMLPurifier_...')
#6 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdown.php(232): yii\helpers\BaseMarkdown::processParagraph('[[HTMLPurifier_...', 'api')
#7 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/views/seeAlso.php(16): yii\apidoc\helpers\ApiMarkdown::process('[[HTMLPurifier_...', Object(yii\apidoc\models\ClassDoc), true)
#8 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(330): require('/home/cloudadic...')
#9 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/cloudadic...', Array)
#10 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/cloudadic...', Array, NULL)
#11 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/views/methodDetails.php(63): yii\base\View->render('seeAlso', Array)
#12 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(330): require('/home/cloudadic...')
#13 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/cloudadic...', Array)
#14 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/cloudadic...', Array, NULL)
#15 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/views/type.php(108): yii\base\View->render('/tem...', Array)
#16 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(330): require('/home/cloudadic...')
#17 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/cloudadic...', Array)
#18 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/cloudadic...', Array, Object(yii\apidoc\templates\bootstrap\ApiRenderer))
#19 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/ApiRenderer.php(135): yii\base\View->render('/tem...', Array, Object(yii\apidoc\templates\bootstrap\ApiRenderer))
#20 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/ApiRenderer.php(105): yii\apidoc\templates\html\ApiRenderer->renderWithLayout('/tem...', Array)
#21 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/bootstrap/ApiRenderer.php(46): yii\apidoc\templates\html\ApiRenderer->render(Object(yii\apidoc\models\Context), './output')
#22 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/commands/ApiController.php(112): yii\apidoc\templates\bootstrap\ApiRenderer->render(Object(yii\apidoc\models\Context), './output')
#23 [internal function]: yii\apidoc\commands\ApiController->actionIndex(Array, './output')
#24 /home/cloudadic/service/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /home/cloudadic/service/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#26 /home/cloudadic/service/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#27 /home/cloudadic/service/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#28 /home/cloudadic/service/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('api', Array)
#29 /home/cloudadic/service/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('api', Array)
#30 /home/cloudadic/service/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#31 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/apidoc(52): yii\base\Application->run()
#32 {main}

**Comment by cebe** [comment]
could it be that you have something like `::]]` somewhere in your code?

**Comment by cebe** [comment]
looks like `$subjectName` is empty here: https://github.com/yiisoft/yii2-apidoc/blob/6ee64b6d7c759020d2f472c5aaa99d81897f524f/helpers/ApiMarkdownTrait.php#L55

**Comment by cebe** [comment]
Fixed, thank you!

**Pull request closed without merging**
