### PR TITLE
TypeDoc adds docblock @propery tags as properties

### PR DESCRIPTION
**Pull request by urmaul**
Basic implementation for #7

### CODE REVIEW

**Comment by cebe** [comment]
thanks for adding this. it may cause problems with properties added via getters and setters in the framework, need to check that before merge.

**Comment by urmaul** [comment]
I see. It will add an error `Property $propertyName conflicts with a defined getter {$method->name} in {$class->name}.`.
https://github.com/yiisoft/yii2-apidoc/blob/master/models/Context.php#L312

**Comment by cebe** [comment]
yeah but it is still a good idea to add it. just need to avoid the conflict.

**Comment by cebe** [comment]
Lets close this for now. The framework auto generates the `@property` docs, this would duplicate the documentation for each magic property. Thanks for the contribution anyway!

**Pull request closed without merging**
